# Lab Assignment 1: Rock, Paper, Scissors

## Write and Run Your Own Code to Implement a Rock-Paper-Scissors Model

In [1]:
# Library Declarations
import numpy as np
import random

np.random.seed(0)
random.seed(0)


In [2]:
# Data extraction here: extract the data from the txt file to python input
# One suggestion is using integers 0,1,2 for rock paper scissor
# and using CPU guess, your guess and score (1 if you win; -1 if you lose; 0 for draw) as possible data
demo_data = np.loadtxt(r"./demo_data.txt", dtype=int) .reshape(-1,3)
print("The data in this file has been stored in a NumPy array of size {}.".format(demo_data.shape))
print(demo_data)

The data in this file has been stored in a NumPy array of size (5, 3).
[[ 0  1  1]
 [ 0  2 -1]
 [ 1  0 -1]
 [ 2  0  1]
 [ 0  0  0]]


In [5]:
np.random.seed(0)
random.seed(0)

history = np.loadtxt(r"./training.txt", dtype=int).reshape(-1,3)
#Define your algorithm here or define your own functions and procedure
def rock_paper_scissor(history=None, last_choice=None):
    # define your function here
    beats = {0: 1, 1: 2, 2: 0} 

    if history is None or len(history) < 2:
        return random.randint(0, 2)

    # transition matrix from move history
    transitions = np.zeros((3, 3), dtype=int)
    for k in range(len(history) - 1):
        cpu_now  = history[k][0]
        cpu_next = history[k + 1][0]
        transitions[cpu_now][cpu_next] += 1

    # predict next move based on last move
    last_cpu_move = history[-1][0]
    row = transitions[last_cpu_move]

    if row.sum() == 0:
        return random.randint(0, 2)

    predicted_cpu_move = np.argmax(row)
    
    return beats[predicted_cpu_move]


In [7]:
print(f'Algorithm says you should choose: {rock_paper_scissor(history)}')

Algorithm says you should choose: 2


## What to Submit?

**Note: This is the first assignment, designed to help you get familiar with the GitHub workflow.**

**For this assignment only**, please submit a `.zip` file containing:
1. Your training data in `training.txt`.
2. Your model evaluation data.
3. A brief write-up describing your algorithm in a couple of sentences, including figures if necessary (your design on paper).
4. Finally, please individually briefly reflect on your experience in a couple of sentences. What are you taking away from this lab?

**Starting from Assignment 2**: Next week, we will release a Google Sheet assigning each student a Lab TA. From Assignment 2 onwards, you will need to:
- Submit a link to your GitHub repository (instead of a .zip file)
- Add your assigned Lab TA as a collaborator to your repository, or they won't be able to grade your work! 